import type { DerivedPlayer } from '@anfpes/engine';
import { getFieldLabel as getFieldLabelFromUtils } from '../utils/playerDisplay';

export const SEARCH_FIELDS: Array<keyof DerivedPlayer> = [
  'NOMBRE',
  'CLUB',
  'NACIONALIDAD',
];

export const POSITION_FIELDS: Array<keyof DerivedPlayer> = [
  'D',
  'E',
  'M',
  'A',
  'R',
  'C',
  'A_1',
  'C_1',
  'I',
  'O',
  'N',
];

export const KEY_STATS: Array<keyof DerivedPlayer> = [
  'PROMEDIO',
  'MEJOR PROMEDIO',
  'PT',
  'LIB',
  'CT',
  'SA',
  'LA',
  'CCD',
  'CC',
  'VOL',
  'MP',
  'EX',
  'SD',
  'DC',
];

export const FAV_SIDE_FIELD = 'FAVOURED SIDE' as keyof DerivedPlayer;
export const INJURY_FIELD = 'TOLERANCIA LESIONES' as keyof DerivedPlayer;
export const FITNESS_FIELD = 'CONDICIÓN FITNESS' as keyof DerivedPlayer;

// Grupos de campos para los filtros con divisores
export const FIELD_GROUPS = [
  {
    label: 'Datos Personales',
    fields: [
      'NACIONALIDAD',
      'CLUB',
      'ANFPES',
      'nro selección',
      'nro clasico',
      'DORSAL',
      'ALTURA',
      'PESO',
      'SKIN COLOR',
      'EDAD',
      'PIE',
      'FAVOURED SIDE',
    ],
  },
  {
    label: 'Promedios',
    fields: [
      'PROMEDIO',
      'MEJOR PROMEDIO',
      'PT',
      'LIB',
      'CT',
      'SA',
      'LA',
      'CCD',
      'CC',
      'VOL',
      'MP',
      'EX',
      'SD',
      'DC',
    ],
  },
  {
    label: 'Stats',
    fields: [
      'ATAQUE',
      'DEFENSA',
      'ESTABILIDAD',
      'RESISTENCIA',
      'VELOCIDAD MÁXIMA',
      'ACELERACIÓN',
      'REPUESTA',
      'AGILIDAD',
      'PRECISIÓN DRIBBLE',
      'VELOCIDAD DRIBBLE',
      'PRECISIÓN   P CORTO',
      'VELOCIDAD  P CORTO',
      'PRECISIÓN       P LARGO',
      'VELOCIDAD     P LARGO',
      'PRECISIÓN DISPARO',
      'POTENCIA DISPARO',
      'TÉCNICA DISPARO',
      'PRECISIÓN TIRO LIBRE',
      'EFECTO',
      'CABEZAZO',
      'SALTO',
      'TÉCNICA',
      'AGRESIVIDAD',
      'MENTALIDAD',
      'ARQUERO',
      'TRABAJO EN EQUIPO',
    ],
  },
  {
    label: 'Atributos Físicos',
    fields: [
      'TOLERANCIA LESIONES',
      'CONSISTENCIA',
      'CONDICIÓN FITNESS',
      'PRECICIÓN PIE MALO',
      'FRECUENCIA PIE MALO',
    ],
  },
  {
    label: 'Habilidades Especiales',
    fields: [
      'REGATE',
      'HAB REGATE',
      'POSICION',
      'REACCION',
      'CAP MANDO',
      'PASES',
      'GOLEADOR',
      '1-1 GOL',
      'JUG POSTE',
      'NO OFFSIDE',
      'MID SHOOT',
      'LADO',
      'CENTRO',
      'PENALES',
      'PASE 1 TOQ',
      'EXTERIOR',
      'MARCA MAN',
      'ENTRADAS',
      'COBERTURA',
      'SI OFFSIDE',
      'PARAPENAL',
      'ACHIQUE 1-1',
      'SAQUE LARG',
    ],
  },
  {
    label: 'Métricas',
    fields: [
      'DESTREZA ATAQUE',
      'DESTREZA DEFENSA',
      'FINIQUITO',
      'VELOCIDAD',
      'EXPLOSIVIDAD',
      'PROMEDIO AGILIDADES',
      'POTENCIA DE PATADA',
      'RECUPERACION DE BALÓN',
      'ALETISMO',
      'JUEGO AEREO',
      'CREATIVIDAD',
    ],
  },
  {
    label: 'MacroStats',
    fields: ['ATK', 'TEC', 'RES', 'DEF', 'FUE', 'VEL'],
  },
];

// Columnas por defecto visibles en la tabla del buscador
export const DEFAULT_TABLE_COLUMNS = [
  'NOMBRE',
  'NACIONALIDAD',
  'CLUB',
  'PROMEDIO',
  'ATAQUE',
  'DEFENSA',
  'VELOCIDAD MÁXIMA',
  'ACELERACIÓN',
  'ESTABILIDAD',
  'REPUESTA',
  'AGILIDAD',
  'TRABAJO EN EQUIPO',
  'TOLERANCIA LESIONES',
  'CONSISTENCIA',
  'CONDICIÓN FITNESS',
] as const;

// Función para obtener el label de header de columna (con abreviaciones para la tabla)
export function getTableHeaderLabel(field: string): string {
  if (field === 'NOMBRE') return 'Jugador';

  // Obtener el label completo del campo usando las reglas normales
  const fullLabel = getFieldLabelFromUtils(field);

  return fullLabel;
}

// Mantiene el orden original de la Hoja 1 (excluyendo columnas ocultas)
export const FIELD_ORDER = [
  'NACIONALIDAD',
  'nro selección',
  'nro clasico',
  'DORSAL',
  'DORSAL_1',
  'ALTURA',
  'PESO',
  'SKIN COLOR',
  'EDAD',
  'PIE',
  'FAVOURED SIDE',
  'CLUB',
  'PROMEDIO',
  'MEJOR PROMEDIO',
  'PT',
  'LIB',
  'CT',
  'SA',
  'LA',
  'CCD',
  'CC',
  'VOL',
  'MP',
  'EX',
  'SD',
  'DC',
  'ATAQUE',
  'DEFENSA',
  'ESTABILIDAD',
  'RESISTENCIA',
  'VELOCIDAD MÁXIMA',
  'ACELERACIÓN',
  'REPUESTA',
  'AGILIDAD',
  'PRECISIÓN DRIBBLE',
  'VELOCIDAD DRIBBLE',
  'PRECISIÓN   P CORTO',
  'VELOCIDAD  P CORTO',
  'PRECISIÓN       P LARGO',
  'VELOCIDAD     P LARGO',
  'PRECISIÓN DISPARO',
  'POTENCIA DISPARO',
  'TÉCNICA DISPARO',
  'PRECISIÓN TIRO LIBRE',
  'EFECTO',
  'CABEZAZO',
  'SALTO',
  'TÉCNICA',
  'AGRESIVIDAD',
  'MENTALIDAD',
  'ARQUERO',
  'TRABAJO EN EQUIPO',
  'TOLERANCIA A LAS LESIONES',
  'CONSISTENCIA',
  'CONDICIÓN FITNESS',
  'PRECICIÓN PIE MALO',
  'FRECUENCIA PIE MALO',
  'REGATE',
  'HAB REGATE',
  'POSICION',
  'REACCION',
  'CAP MANDO',
  'PASES',
  'GOLEADOR',
  '1-1 GOL',
  'JUG POSTE',
  'NO OFFSIDE',
  'MID SHOOT',
  'LADO',
  'CENTRO',
  'PENALES',
  'PASE 1 TOQ',
  'EXTERIOR',
  'MARCA MAN',
  'ENTRADAS',
  'COBERTURA',
  'SI OFFSIDE',
  'PARAPENAL',
  'ACHIQUE 1-1',
  'SAQUE LARG',
  'DESTREZA ATAQUE',
  'DESTREZA DEFENSA',
  'FINIQUITO',
  'VELOCIDAD',
  'EXPLOSIVIDAD',
  'PROMEDIO AGILIDADES',
  'POTENCIA DE PATADA',
  'RECUPERACION DE BALÓN',
  'ALETISMO',
  'JUEGO AEREO',
  'CREATIVIDAD',
  'ATK',
  'TEC',
  'RES',
  'DEF',
  'FUE',
  'VEL',
];
