import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const flagsDir = path.join(__dirname, '../../../apps/ui/public/images/flags');
const clubsDir = path.join(__dirname, '../../../apps/ui/public/images/clubs');

// Mapeo de países (del Excel que me diste)
const COUNTRY_MAPPING: Record<string, string> = {
  Albania: '296',
  Algeria: '197',
  Angola: '198',
  Argentina: '199',
  Armenia: '3',
  Australia: '200',
  Austria: '201',
  Belarus: '2',
  Belgium: '202',
  Benin: '203',
  Bolivia: '204',
  'Bosnia and Herzegovina': '205',
  Brazil: '206',
  Bulgaria: '207',
  'Burkina Faso': '208',
  Cameroon: '209',
  Canada: '1',
  'Cape Verde': '210',
  Chile: '211',
  China: '212',
  Colombia: '213',
  'Costa Rica': '214',
  "Cote d'Ivoire": '215',
  Croatia: '216',
  Cyprus: '217',
  'Czech Republic': '218',
  Denmark: '219',
  'DR Congo': '220',
  Ecuador: '221',
  Egypt: '222',
  England: '223',
  'Equatorial Guinea': '224',
  Estonia: '225',
  Finland: '226',
  France: '227',
  Gabon: '228',
  Gambia: '229',
  Georgia: '230',
  Germany: '231',
  Ghana: '232',
  Greece: '233',
  Grenada: '234',
  Guadeloupe: '235',
  Guinea: '236',
  'Guinea-Bissau': '237',
  Honduras: '238',
  Hungary: '239',
  Iceland: '240',
  Iran: '241',
  Ireland: '242',
  Israel: '243',
  Italy: '244',
  Jamaica: '245',
  Japan: '246',
  Kenya: '247',
  Latvia: '248',
  Liberia: '249',
  Libya: '250',
  Liechtenstein: '251',
  Lithuania: '252',
  Macedonia: '253',
  Mali: '254',
  Martinique: '255',
  Mexico: '256',
  Morocco: '257',
  Mozambique: '258',
  Netherlands: '259',
  'Netherlands Antilles': '260',
  'New Zealand': '261',
  Nigeria: '262',
  'Northern Ireland': '263',
  Norway: '264',
  Oman: '265',
  Panama: '266',
  Paraguay: '267',
  Peru: '268',
  Poland: '269',
  Portugal: '270',
  Romania: '271',
  Russia: '272',
  'Saudi Arabia': '273',
  Scotland: '274',
  Senegal: '275',
  'Serbia and Montenegro': '276',
  'Sierra Leone': '277',
  Slovakia: '278',
  Slovenia: '279',
  'South Africa': '280',
  'South Korea': '281',
  Spain: '282',
  Sweden: '283',
  Switzerland: '284',
  Togo: '285',
  'Trinidad and Tobago': '286',
  Tunisia: '287',
  Turkey: '288',
  Ukraine: '289',
  Uruguay: '290',
  'United States': '291',
  Uzbekistan: '292',
  Venezuela: '293',
  Wales: '294',
  Zimbabwe: '295',
};

// Mapeo de clubs
const CLUB_MAPPING: Record<string, string> = {
  'A.C. Milan': '4',
  'A.S. Roma': '5',
  'AC Sparta Praha': '6',
  'ADO Den Haag': '7',
  'AJ Auxerre': '8',
  Ajax: '9',
  Arsenal: '10',
  'R. Madrid': '11',
  'AS Monaco': '12',
  'AS Nancy-Lorraine': '13',
  'AS Saint-Étienne': '14',
  Ascoli: '15',
  'Aston Villa FC': '16',
  Atalanta: '17',
  'Athletic Club': '18',
  AZ: '19',
  'Bayern München': '20',
  Benfica: '21',
  'Besiktas JK': '22',
  'Blackburn Rovers FC': '23',
  'Boca Juniors': '24',
  'Selección South Africa': '25',
  'Sevilla F.C.': '26',
  'Bolton Wanderers FC': '28',
  'C. Gimnastic': '29',
  'C.A. Osasuna': '30',
  Cagliari: '31',
  Catania: '32',
  Celtic: '33',
  'Charlton Athletic FC': '34',
  'Chelsea FC': '35',
  'Chievo Verona': '36',
  'Club Brugge KV': '44',
  'CS Sedan': '45',
  'Djurgardens IF': '46',
  Empoli: '48',
  'ES Troyes AC': '50',
  'Everton FC': '51',
  'F.C. Barcelona': '52',
  'F.C. Copenhagen': '53',
  'FC Groningen': '54',
  'FC Lorient': '55',
  'FC Nantes-Atlantique': '56',
  'FC Porto': '57',
  'FC Sochaux': '58',
  'FC Twente': '59',
  'FC Utrecht': '60',
  Feyenoord: '62',
  Fiorentina: '63',
  'Fulham FC': '64',
  Galatasaray: '65',
  'Getafe C.F.': '66',
  'Girondins de Bordeaux': '67',
  Inter: '68',
  Lazio: '70',
  'Le Mans UC 72': '71',
  'Levante U.D.': '72',
  'Lille OSC': '73',
  'Liverpool FC': '74',
  Livorno: '75',
  'Manchester City': '76',
  'Manchester United': '77',
  Messina: '78',
  'Middlesbrough FC': '79',
  'N.E.C. Nijmegen': '82',
  'NAC Breda': '83',
  'Newcastle United FC': '84',
  'OGC Nice': '85',
  'Olympiacos Piraeus': '86',
  'Olympique de Marseille': '87',
  Palermo: '89',
  'Panathinaikos FC': '90',
  'Paris Saint-Germain': '91',
  Parma: '92',
  'PES United': '93',
  'Portsmouth FC': '94',
  'PSV Eindhoven': '95',
  'R. Betis': '96',
  'R. Racing C.': '97',
  'R. Sociedad': '98',
  'R. Zaragoza': '99',
  'R.C. Celta': '100',
  'R.C. Deportivo la Coruña': '101',
  'R.C. Recreativo de Huelva': '102',
  'R.C.D. Espanyol': '103',
  'R.C.D. Mallorca': '104',
  Rangers: '105',
  'RC Lens': '106',
  'Reading FC': '107',
  Reggina: '108',
  'River Plate': '109',
  'RKC Waalwijk': '110',
  'Roda JC': '111',
  'Rosenborg BK': '112',
  Sampdoria: '114',
  'Sao Paulo FC': '115',
  'SBV Excelsior': '116',
  'SC Heerenveen': '117',
  'Selección Angola': '118',
  'Selección Argentina': '119',
  'Selección Australia': '120',
  'Selección Austria': '121',
  'Selección Belgium': '122',
  'Selección Bulgaria': '123',
  'Selección Cameroon': '124',
  'Selección Chile': '125',
  'Selección Colombia': '126',
  'Selección Costa Rica': '127',
  "Selección Cote d'Ivoire": '128',
  'Selección Croatia': '129',
  'Selección Czech Republic': '130',
  'Selección Denmark': '131',
  'Selección Ecuador': '132',
  'Selección England': '133',
  'Selección Finland': '134',
  'Selección France': '135',
  'Selección Germany': '136',
  'Selección Ghana': '137',
  'Selección Greece': '138',
  'Selección Hungary': '139',
  'Selección Iran': '140',
  'Selección Ireland': '141',
  'Selección Italy': '142',
  'Selección Japan': '143',
  'Selección Latvia': '144',
  'Selección Mexico': '145',
  'Selección Netherlands': '146',
  'Selección Nigeria': '147',
  'Selección Northern Ireland': '148',
  'Selección Norway': '149',
  'Selección Paraguay': '150',
  'Selección Peru': '151',
  'Selección Poland': '152',
  'Selección Portugal': '153',
  'Selección Romania': '154',
  'Selección Russia': '155',
  'Selección Saudi Arabia': '156',
  'Selección Scotland': '157',
  'Selección Serbia and Montenegro': '158',
  'Selección Slovakia': '159',
  'Selección Slovenia': '160',
  'Selección South Korea': '161',
  'Selección Spain': '162',
  'Selección Switzerland': '164',
  'Selección Togo': '165',
  'Selección Trinidad and Tobago': '166',
  'Selección Tunisia': '167',
  'Selección Turkey': '168',
  'Selección Ukraine': '169',
  'Selección Uruguay': '170',
  'Selección United States': '171',
  'Selección Wales': '172',
  'Sheffield United FC': '173',
  Siena: '179',
  'Sparta Rotterdam': '180',
  'Sporting Lisbon': '181',
  'Stade Rennais FC': '182',
  Torino: '183',
  'Tottenham Hotspur FC': '184',
  'Toulouse FC': '185',
  Udinese: '186',
  'Valencia C.F.': '187',
  'Valenciennes FC': '188',
  'Villarreal C.F.': '189',
  Vitesse: '190',
  'Watford FC': '191',
  'WE United': '192',
  'West Ham United FC': '193',
  'Wigan Athletic FC': '194',
  'Selección Brazil': '196',
  'Willem II': '298',
  'C. Atlético Madrid': '297',
  'Heracles Almelo': '507',
};

function findImageFile(dir: string, imageNumber: string): string | null {
  const files = fs.readdirSync(dir);
  const found = files.find((f) => {
    const match = f.match(/^image(\d+)\.(png|jpeg|jpg|webp|gif)$/i);
    return match && match[1] === imageNumber;
  });
  return found || null;
}

console.log('🔍 Generando mapeos automáticos...\n');

// Generar mapeo de banderas
console.log('// Banderas - Mapeo de países a imágenes del Excel');
console.log('export const COUNTRY_FLAG_MAPPING: Record<string, string> = {');
Object.entries(COUNTRY_MAPPING).forEach(([country, num]) => {
  const file = findImageFile(flagsDir, num);
  if (file) {
    console.log(`  '${country}': '${file}',`);
  } else {
    console.log(`  // '${country}': 'image${num}.??? - NO ENCONTRADA',`);
  }
});
console.log('};\n');

// Generar mapeo de clubs
console.log('// Mapeo completo de clubes a imágenes del Excel');
console.log('export const CLUB_SHIELDS_MAPPING: Record<string, string> = {');
Object.entries(CLUB_MAPPING).forEach(([club, num]) => {
  const file = findImageFile(clubsDir, num);
  if (file) {
    console.log(`  '${club}': '${file}',`);
  } else {
    console.log(`  // '${club}': 'image${num}.??? - NO ENCONTRADA',`);
  }
});
console.log('};');
